spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:study
    username: study
    password: 123456
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.xiaoyu.springboot.entity